{#- SPDX-License-Identifier: AGPL-3.0-or-later -#}
{#- Copyright (C) 2025 Mingyuan Xiang -#}
TOOLS_REL_ROOT = tools
# TOOLS =
TOOLCHAINS = gcc

APPS = blink external_timer playground {{ model_name }}

export DEVICE = msp430fr5994
export BOARD = launchpad 

include tools/maker/Makefile
