/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2025 Mingyuan Xiang
 */

#ifndef INCLUDE_MSPIO_UARTIO_MSG_H
#define INCLUDE_MSPIO_UARTIO_MSG_H

#define UARTIO_MSG_TYPE_PRINTF_STR 0x1f
#define UARTIO_MSG_TYPE_BYTES 0x2f
#define UARTIO_MSG_TYPE_MAT 0x3f
#define UARTIO_MSG_TYPE_RECV_DONE 0x4f

#define UARTIO_BUFFER_SIZE 100
#define UARTIO_16BIT_BUFFER_SIZE UARTIO_BUFFER_SIZE / 2

#define UARTIO_STRING_END 0xf0

#endif /* INCLUDE_MSPIO_UARTIO_MSG_H */