# Adjust these if using a sleeper inside a stop watch while using smclk for stop watch.
LIBTIMER_TIMEKEEPER_SLEEP ?= LPM3

# This library provides timekeeper functionlity as follows,
#    stop_watch : measures how long a function takes using lfxt
#                 accurate, but cannot be run intermittently
#    sleep_timer: sleeps for a certain duration
#
# Each module/functionality in this library uses a different timer
# to prevent clashes. If using other libraries that use timers,
# change the timers used below.
#

LIBTIMER_STOPWATCH_TIMER ?= 1
LIBTIMER_SLEEP_TIMER ?= 2
LIBTIMER_ALPACA ?=
