EXEC = {{ model_name }}

OBJECTS = main.o {{model_name}}.o buffer/input.o buffer/buffer.o{%for l in layer_list%} layers/{{l}}.o{%endfor%}{%for l in layers_with_weights%} params/{{l}}.o{%endfor%}

DEPS = libdsp:gcc libmsptimer:gcc libmspsyncioutils:gcc libmatAbstract:gcc libfixedAbstract:gcc libmspprintf:gcc libmspio:gcc libmspdriver:gcc libmsp:gcc

# clock config
export LIBMSP_CLK_DCOFREQ = 8
export LIBMSP_CLK_MCLK_DIV = 1

# print config
export LIBUARTIO0_INT_ENABLE = 1
export LIBMSPPRINTF_PRINT_PORT =  0

override CFLAGS += -Wno-pointer-to-int-cast
override CFLAGS += -Wno-missing-braces
include tools/maker/Makefile