#ifndef INTERMITTENT_H
#define INTERMITTENT_H

#define COMPUTE_CK 0
#define COMPUTE_SWITCH 1
#define COMPUTE_IN_CH 2
#define COMPUTE_OUT_CH 3
#define COMPUTE_IO_ROW 4
#define COMPUTE_IO_COL 5
#define MAIN_LOOP 6
#define COUNTER 7

#define GET_OFFSET(x) ((x) * 2)

#define DOUBLE_BUFFER_COMPLETE 0x7FFF // Complete double buffering. No need for recovery
#define DOUBLE_BUFFER_WRITE 0x8000 // Finish transferring to temporary buffer

#define PAD_START 0
#define PAD_MAIN 1
#define PAD_TRANSFER 2
#define PAD_MEMSET 3
#define PAD_END 4
#define MAC_PREPARE 5
#define MAC_COMPUTE 6
#define MAC_END 7

/* INTERMITTENT_LeNet_START has to be 0 */

#define INTERMITTENT_DS_CNN_inter_START 0
#define INTERMITTENT_conv1_Conv_PREPARE 1
#define INTERMITTENT_conv1_Conv_MAIN 2
#define INTERMITTENT_conv1_Conv_BIAS 3
#define INTERMITTENT_conv1_Conv_EXIT 4
#define INTERMITTENT_conv1_Conv_DMA 5
#define INTERMITTENT_relu1_Clip_PREPARE 6
#define INTERMITTENT_relu1_Clip_MAIN 7
#define INTERMITTENT_relu1_Clip_BIAS 8
#define INTERMITTENT_relu1_Clip_EXIT 9
#define INTERMITTENT_relu1_Clip_DMA 10
#define INTERMITTENT_block1_dw_conv_Conv_PREPARE 11
#define INTERMITTENT_block1_dw_conv_Conv_MAIN 12
#define INTERMITTENT_block1_dw_conv_Conv_BIAS 13
#define INTERMITTENT_block1_dw_conv_Conv_EXIT 14
#define INTERMITTENT_block1_dw_conv_Conv_DMA 15
#define INTERMITTENT_block1_dw_relu_Clip_PREPARE 16
#define INTERMITTENT_block1_dw_relu_Clip_MAIN 17
#define INTERMITTENT_block1_dw_relu_Clip_BIAS 18
#define INTERMITTENT_block1_dw_relu_Clip_EXIT 19
#define INTERMITTENT_block1_dw_relu_Clip_DMA 20
#define INTERMITTENT_block1_pw_conv_Conv_PREPARE 21
#define INTERMITTENT_block1_pw_conv_Conv_MAIN 22
#define INTERMITTENT_block1_pw_conv_Conv_BIAS 23
#define INTERMITTENT_block1_pw_conv_Conv_EXIT 24
#define INTERMITTENT_block1_pw_conv_Conv_DMA 25
#define INTERMITTENT_block1_pw_relu_Clip_PREPARE 26
#define INTERMITTENT_block1_pw_relu_Clip_MAIN 27
#define INTERMITTENT_block1_pw_relu_Clip_BIAS 28
#define INTERMITTENT_block1_pw_relu_Clip_EXIT 29
#define INTERMITTENT_block1_pw_relu_Clip_DMA 30
#define INTERMITTENT_block2_dw_conv_Conv_PREPARE 31
#define INTERMITTENT_block2_dw_conv_Conv_MAIN 32
#define INTERMITTENT_block2_dw_conv_Conv_BIAS 33
#define INTERMITTENT_block2_dw_conv_Conv_EXIT 34
#define INTERMITTENT_block2_dw_conv_Conv_DMA 35
#define INTERMITTENT_block2_dw_relu_Clip_PREPARE 36
#define INTERMITTENT_block2_dw_relu_Clip_MAIN 37
#define INTERMITTENT_block2_dw_relu_Clip_BIAS 38
#define INTERMITTENT_block2_dw_relu_Clip_EXIT 39
#define INTERMITTENT_block2_dw_relu_Clip_DMA 40
#define INTERMITTENT_block2_pw_conv_Conv_PREPARE 41
#define INTERMITTENT_block2_pw_conv_Conv_MAIN 42
#define INTERMITTENT_block2_pw_conv_Conv_BIAS 43
#define INTERMITTENT_block2_pw_conv_Conv_EXIT 44
#define INTERMITTENT_block2_pw_conv_Conv_DMA 45
#define INTERMITTENT_block2_pw_relu_Clip_PREPARE 46
#define INTERMITTENT_block2_pw_relu_Clip_MAIN 47
#define INTERMITTENT_block2_pw_relu_Clip_BIAS 48
#define INTERMITTENT_block2_pw_relu_Clip_EXIT 49
#define INTERMITTENT_block2_pw_relu_Clip_DMA 50
#define INTERMITTENT_block3_dw_conv_Conv_PREPARE 51
#define INTERMITTENT_block3_dw_conv_Conv_MAIN 52
#define INTERMITTENT_block3_dw_conv_Conv_BIAS 53
#define INTERMITTENT_block3_dw_conv_Conv_EXIT 54
#define INTERMITTENT_block3_dw_conv_Conv_DMA 55
#define INTERMITTENT_block3_dw_relu_Clip_PREPARE 56
#define INTERMITTENT_block3_dw_relu_Clip_MAIN 57
#define INTERMITTENT_block3_dw_relu_Clip_BIAS 58
#define INTERMITTENT_block3_dw_relu_Clip_EXIT 59
#define INTERMITTENT_block3_dw_relu_Clip_DMA 60
#define INTERMITTENT_block3_pw_conv_Conv_PREPARE 61
#define INTERMITTENT_block3_pw_conv_Conv_MAIN 62
#define INTERMITTENT_block3_pw_conv_Conv_BIAS 63
#define INTERMITTENT_block3_pw_conv_Conv_EXIT 64
#define INTERMITTENT_block3_pw_conv_Conv_DMA 65
#define INTERMITTENT_block3_pw_relu_Clip_PREPARE 66
#define INTERMITTENT_block3_pw_relu_Clip_MAIN 67
#define INTERMITTENT_block3_pw_relu_Clip_BIAS 68
#define INTERMITTENT_block3_pw_relu_Clip_EXIT 69
#define INTERMITTENT_block3_pw_relu_Clip_DMA 70
#define INTERMITTENT_block4_dw_conv_Conv_PREPARE 71
#define INTERMITTENT_block4_dw_conv_Conv_MAIN 72
#define INTERMITTENT_block4_dw_conv_Conv_BIAS 73
#define INTERMITTENT_block4_dw_conv_Conv_EXIT 74
#define INTERMITTENT_block4_dw_conv_Conv_DMA 75
#define INTERMITTENT_block4_dw_relu_Clip_PREPARE 76
#define INTERMITTENT_block4_dw_relu_Clip_MAIN 77
#define INTERMITTENT_block4_dw_relu_Clip_BIAS 78
#define INTERMITTENT_block4_dw_relu_Clip_EXIT 79
#define INTERMITTENT_block4_dw_relu_Clip_DMA 80
#define INTERMITTENT_block4_pw_conv_Conv_PREPARE 81
#define INTERMITTENT_block4_pw_conv_Conv_MAIN 82
#define INTERMITTENT_block4_pw_conv_Conv_BIAS 83
#define INTERMITTENT_block4_pw_conv_Conv_EXIT 84
#define INTERMITTENT_block4_pw_conv_Conv_DMA 85
#define INTERMITTENT_block4_pw_relu_Clip_PREPARE 86
#define INTERMITTENT_block4_pw_relu_Clip_MAIN 87
#define INTERMITTENT_block4_pw_relu_Clip_BIAS 88
#define INTERMITTENT_block4_pw_relu_Clip_EXIT 89
#define INTERMITTENT_block4_pw_relu_Clip_DMA 90
#define INTERMITTENT_avgpool_GlobalAveragePool_PREPARE 91
#define INTERMITTENT_avgpool_GlobalAveragePool_MAIN 92
#define INTERMITTENT_avgpool_GlobalAveragePool_BIAS 93
#define INTERMITTENT_avgpool_GlobalAveragePool_EXIT 94
#define INTERMITTENT_avgpool_GlobalAveragePool_DMA 95
#define INTERMITTENT_Flatten_PREPARE 96
#define INTERMITTENT_Flatten_MAIN 97
#define INTERMITTENT_Flatten_BIAS 98
#define INTERMITTENT_Flatten_EXIT 99
#define INTERMITTENT_Flatten_DMA 100
#define INTERMITTENT_classifier_Gemm_PREPARE 101
#define INTERMITTENT_classifier_Gemm_MAIN 102
#define INTERMITTENT_classifier_Gemm_BIAS 103
#define INTERMITTENT_classifier_Gemm_EXIT 104
#define INTERMITTENT_classifier_Gemm_DMA 105
#define INTERMITTENT_DS_CNN_inter_END 106

#endif