
# Clock Spec
# The base clock sources are as follows,
#    LFXTCLK: 32768 Hz, crystal takes a bit to settle (>800 ms), so cannot use
#    HFXTCLK: 4-24M Hz, crystal, energy hungry
#    VLOCLK: typical 10k Hz, very low power but inaccurate, BAD (about 8.3kHZ?)
#    DCOCLK: variable, controlled by digital oscilations, main clock
#    MODCLK: typical 5M Hz, internal LP, OK power, can be inaccurate
#    LFMODCLK: above divided by 128
#
# The clock signals available are,
#    ACLK: Auxiliary clock
#    MCLK: Master clock, used bu CPU and most of system
#    SMCLK: Subsystem master clock. Mostly used by peripherals
#    MODCLK: Module clock, may be used by peripherals, etc.
#    VLOCLK: VLO clock, may be used by peripherals, etc.
#
# Note that the MODCLK and VLOCLK are enabled if you are using them.
# To not turn them on, don't use them as clock sources. Save the energy.
#
# The values you SHOULD define are as follow,
# DCOFREQ : DCO frequency. Valid values are (in 1 MHZ):
#             1, 4, 8 
#
# ACLK_SRC: LFXTCLK, VLOCLK or LFMODCLK
#
# SMCLK_SRC: LFXTCLK, VLOCLK, LFMODCLK, DCOCLK, MODCLK, HFXTCLK
#
# MCLK_SRC: LFXTCLK, VLOCLK, LFMODCLK, DCOCLK, MODCLK, HFXTCLK
#
# ACLK_DIV, SMCLK_DIV, MCLK_DIV: 1,2,4,8,16,32
LIBMSP_CLK_DCOFREQ   ?= 1
LIBMSP_CLK_ACLK_SRC  ?= VLOCLK
LIBMSP_CLK_MCLK_SRC  ?= DCOCLK
LIBMSP_CLK_SMCLK_SRC ?= DCOCLK

LIBMSP_CLK_ACLK_DIV  ?= 1
LIBMSP_CLK_MCLK_DIV  ?= 1
LIBMSP_CLK_SMCLK_DIV ?= 1
